#!/usr/bin/env python3
"""Single entry point. Run everything with one command:

    python run.py

What it does, in order:
  1. refuses to continue unless you are OFFLINE, then arms a background
     kill-switch that hard-stops everything if the network comes back;
  2. wipes everything a previous run generated (DB + CSVs + frontend build) so
     each run rebuilds from scratch — data/inbox is never touched;
  3. if there are statements in data/inbox/, prompts for the PDF password
     (typed once, kept only in memory — never written to disk) and ingests them;
  4. launches the viewer API and the frontend in the background;
  5. opens the dashboard in your browser.

Press Ctrl+C to shut everything down.
"""

import argparse
import glob
import os
import shutil
import signal
import socket
import subprocess
import sys
import time
import webbrowser

ROOT = os.path.dirname(os.path.abspath(__file__))
BACKEND = os.path.join(ROOT, "backend")
FRONTEND = os.path.join(ROOT, "frontend")
DATA = os.path.join(ROOT, "data")
INBOX = os.path.join(DATA, "inbox")
CSV_DIR = os.path.join(DATA, "csv")

API_PORT = 8000
FRONTEND_PORT = 5173

sys.path.insert(0, BACKEND)

import offline_guard  # noqa: E402

_children: list[subprocess.Popen] = []


def _cleanup() -> None:
    # Kill each child's whole process GROUP, not just the launcher. `npm run dev`
    # spawns vite as a child; terminating npm alone would orphan vite and leave
    # the frontend serving. start_new_session=True (below) puts each child in its
    # own group so killpg takes the launcher and everything it spawned.
    for p in _children:
        try:
            os.killpg(os.getpgid(p.pid), signal.SIGTERM)
        except Exception:
            try:
                p.terminate()
            except Exception:
                pass


def _reset_state() -> None:
    """Wipe everything generated by a previous run so each run rebuilds from
    scratch. The inbox (your source PDFs) is never touched.

    This matters because ingestion dedupes: without a reset, rows already in the
    DB would be skipped and stale/incorrect data from an earlier run would
    survive. Clearing the DB also resets what the frontend shows (it has no
    persisted state of its own — it only renders the DB via the API).
    """
    removed = []
    for db in glob.glob(os.path.join(DATA, "db.sqlite*")):  # incl -wal / -shm
        os.remove(db)
        removed.append(os.path.relpath(db, ROOT))
    if os.path.isdir(CSV_DIR):                               # normalised + raw dumps
        shutil.rmtree(CSV_DIR)
        removed.append(os.path.relpath(CSV_DIR, ROOT) + "/")
    dist = os.path.join(FRONTEND, "dist")                    # any stale frontend build
    if os.path.isdir(dist):
        shutil.rmtree(dist)
        removed.append(os.path.relpath(dist, ROOT) + "/")
    print("[reset] cleared: " + (", ".join(removed) if removed else "nothing (already clean)"))


def _wait_port(port: int, timeout: float = 60.0) -> bool:
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            with socket.create_connection(("127.0.0.1", port), timeout=1):
                return True
        except OSError:
            time.sleep(0.5)
    return False


def _present_banks(statements: list[str]) -> dict[str, int]:
    """{bank name: file count} for the inbox files that match a known bank."""
    import banks
    counts: dict[str, int] = {}
    for f in statements:
        cfg = banks.route(os.path.basename(f))
        if cfg:
            counts[cfg.name] = counts.get(cfg.name, 0) + 1
    return counts


def _select_banks(present: dict[str, int], cli: str | None) -> set[str]:
    """Decide which banks to process — from --banks, or an interactive picker.

    The list of choices comes from whichever banks actually have files in the
    inbox, so new banks appear automatically once the registry knows them.
    """
    import banks
    available = sorted(present)

    # non-interactive: --banks sbi,ubi  (or 'all')
    if cli:
        if cli.strip().lower() == "all":
            return set(available)
        chosen: set[str] = set()
        for tok in cli.replace(",", " ").split():
            cfg = banks.resolve(tok)
            if cfg is None:
                print(f"[banks] unknown bank '{tok}', ignoring")
            elif cfg.name not in present:
                print(f"[banks] '{cfg.name}' has no files in the inbox, ignoring")
            else:
                chosen.add(cfg.name)
        return chosen or set(available)

    # interactive picker (no point asking when only one bank is present)
    if len(available) <= 1:
        return set(available)
    print("\nBanks found in inbox:")
    for i, name in enumerate(available, 1):
        count = present[name]
        print(f"  [{i}] {name}  ({count} file{'s' if count != 1 else ''})")
    try:
        raw = input("Select banks — numbers/names comma-separated, or Enter for all: ").strip()
    except EOFError:
        raw = ""
    if not raw:
        return set(available)
    chosen = set()
    for tok in raw.replace(",", " ").split():
        if tok.isdigit() and 1 <= int(tok) <= len(available):
            chosen.add(available[int(tok) - 1])
        else:
            cfg = banks.resolve(tok)
            if cfg and cfg.name in present:
                chosen.add(cfg.name)
    return chosen or set(available)


def main() -> None:
    parser = argparse.ArgumentParser(description="Offline finance manager")
    parser.add_argument(
        "--banks", metavar="LIST",
        help="comma-separated banks to process, e.g. 'sbi', 'sbi,ubi' or 'all'. "
             "If omitted, you're asked when more than one bank has files in the inbox.",
    )
    args = parser.parse_args()

    os.makedirs(INBOX, exist_ok=True)

    # 1. offline guard (startup check + continuous kill-switch that also
    #    tears down the child servers if the network reappears)
    print("[guard] checking connectivity...")
    offline_guard.assert_offline()
    print("[guard] OFFLINE ✓  arming kill-switch (checks every 3s)")
    offline_guard.arm(cleanup=_cleanup)

    # 2. clean slate — remove everything a previous run generated (DB + CSVs +
    #    any frontend build). The inbox is left untouched.
    _reset_state()

    # 3. choose banks, then ingest. Selection + passwords are asked AFTER the
    #    guard has confirmed we're offline. Each selected bank with a PDF gets
    #    its own password prompt.
    import banks
    statements = [f for f in glob.glob(os.path.join(INBOX, "*"))
                  if f.lower().endswith((".pdf", ".csv"))]
    present = _present_banks(statements)
    if not present:
        if statements:
            print("[ingest] files are in the inbox but none match a known bank prefix "
                  f"({', '.join(banks.names())}) — rename them e.g. sbi_*.pdf")
        else:
            print("[ingest] data/inbox is empty — dashboard will be empty until you "
                  "add statements and re-run.")
    else:
        import getpass
        import ingest
        selected = _select_banks(present, args.banks)
        print(f"[banks] processing: {', '.join(sorted(selected))}")
        passwords = {
            name: (getpass.getpass(f"{name} PDF password (leave blank if none): ") or None)
            for name in ingest.banks_needing_password(INBOX) if name in selected
        }
        ingest.run_ingest(INBOX, passwords, only=selected)

    # 4. launch viewer API + frontend in the background
    print(f"[serve] starting API on :{API_PORT} and frontend on :{FRONTEND_PORT} ...")
    _children.append(subprocess.Popen(
        [sys.executable, "-m", "uvicorn", "app:app", "--port", str(API_PORT)],
        cwd=BACKEND, env=os.environ.copy(), start_new_session=True,
    ))
    _children.append(subprocess.Popen(
        ["npm", "run", "dev"], cwd=FRONTEND, env=os.environ.copy(),
        start_new_session=True,
    ))

    # 5. open the browser once the frontend is up
    if _wait_port(FRONTEND_PORT):
        url = f"http://localhost:{FRONTEND_PORT}"
        webbrowser.open(url)
        print(f"\n  Dashboard ready → {url}   (Ctrl+C to stop)\n")
    else:
        print("[serve] frontend didn't come up in time — check the npm output above.")

    # 6. stay alive until Ctrl+C or a server dies
    try:
        while True:
            time.sleep(1)
            if any(p.poll() is not None for p in _children):
                print("[serve] a server process exited — shutting down.")
                break
    except KeyboardInterrupt:
        print("\nShutting down...")
    finally:
        _cleanup()


if __name__ == "__main__":
    main()
